### ISSUE TITLE
Conflict between react-native-picker-select and Blinks SDK Causes Invariant Violation Error

### ISSUE THREAD

**Issue by ramyodev** [dialectlabs/blinks-react-native#6]
# Issue Summary
When using `react-native-picker-select` in a project that also incorporates the Blinks SDK, the application fails with an invariant violation error. This issue appears related to a conflict over the registration of the `RNCPicker` view component when the Hermes JS engine is in use.

## Steps to Reproduce
1. Install `react-native-picker-select` and Blinks SDK in a React Native project.
2. Import and use `Picker` from `react-native-picker-select` as shown in the example below:
   ```javascript
   import Picker from 'react-native-picker-select';
   {placeholder && <Picker onValueChange={handleCountryCodeChange} items={COUNTRY_CODES} style={pickerSelectStyles} placeholder={placeholder} />}
   ```
3. Run the application using the Hermes engine.

## Expected Behavior
The application should load without errors, allowing the Picker and Blinks SDK to function simultaneously.

## Actual Behavior
The application throws an error upon startup:
```
ERROR Invariant Violation: Tried to register two views with the same name RNCPicker, js engine: hermes
```

## Environment
- React Native version: `0.74.3`
- `react-native-picker-select` version: `^9.1.3`
- `@dialectlabs/blinks` version: `^0.8.0`
- `@dialectlabs/blinks-react-native` version: `^0.2.0`

**Comment by prsvic** [comment]
Hey @ramyodev,

This might be caused by having two different versions of the `@react-native-picker/picker` library installed. The `react-native-picker-select` library requires a peer dependency on `@react-native-picker/picker`, and the Blinks SDK also brings it as a dependency.

Could you check your `yarn.lock` (or whichever lock file you’re using)?

If you do find two versions, try resolving them to a single version and please let me know if the issue still persists.

**Comment by ramyodev** [comment]
Yes this was fixed by a package resolution. 

If anyone else faces that issue, in our case we resolved it like so:

```
	"resolutions": {
		"@react-native-picker/picker": "2.7.7"
	},
```
